name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build_and_run_tests:
    name: "Build and Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - wgpu
          - f64
    steps:
    - uses: "actions/checkout@v4"
    - run: sudo apt-get update
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with: 
        packages: mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers
        version: 1.0
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: Swatinem/rust-cache@v2

    - name: Build crate
      run: cargo build --verbose --tests --features ${{ matrix.features }}
    - name: Run cargo tests
      run: cargo test --verbose --features ${{ matrix.features }}
    - name: Run clippy.
      run: cargo clippy --verbose --tests --features ${{ matrix.features }}
    - name: Build docs
      run: cargo doc --no-deps --features ${{ matrix.features }}

  rustfmt:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
